version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DJANGO_DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:8000
      - DJANGO_SECRET_KEY=change_this_to_a_secure_secret_key_in_production
    volumes:
      - ./backend/schedule.xlsx:/app/backend/schedule.xlsx
    command: >
      sh -c "cd /app/backend && 
             python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
