version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DJANGO_DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_SECRET_KEY=dev_secret_key_for_local_use_only
    volumes:
      - ./backend/schedule.xlsx:/app/backend/schedule.xlsx
    command: >
      sh -c "cd /app/backend && 
             python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
